### ISSUE TITLE
[feature request] Use custom sort recursively on the whole file

### ISSUE THREAD

**Issue by RodriguezLucha** [pascalre/vscode-yaml-sort#10]
Can the custom sort order be extended so that it works recursively on the whole file? I do see that it is sorting the whole file but the custom sort order seem to be only applied at the top level?

Im using this to get a custom sort on a swagger yml file:

For example:

```
top_thing:
  /some_path:
    get:
      description: returns a list of things
      parameters:
        - in: query
          name: color     <---- I would like 'name' to appear before 'in', sorting keeps moving this down
          required: false
          type: string
        - in: query
          name: width
          required: false
          type: number
```

In the meantime I did this:
https://gist.github.com/RodriguezLucha/1dda9637d32fc085533774cf63dd3c29
