### ISSUE TITLE
Add mecanics that sorts `YAML` blocks of defined level

### ISSUE THREAD

**Issue by Gregory108** [pascalre/vscode-yaml-sort#100]
Hello!
Not sure it is easily possible. As far as I understand, currently the plugin sorts keys inside the last leaves of the `yaml` "tree" alphabetically or along with custom order.

I do not want to change insides of the keys. But I do want to sort alphabetically by the values of the keys of a certain level. E.g. I want convent this:
```yaml
models:
  - name: database_name
    tables:
      - name: B_table_name
        description: >
          Something 1
      - name: A_table_name
        meta:
          owner: me
        description: >
          Something 2
          
          * markdown item 1

          * markdown item 2

```
Into this:
```yaml
models:
  - name: database_name
    tables:
      - name: A_table_name
        meta:
          owner: me
        description: >
          Something 2
          
          * markdown item 1

          * markdown item 2
      
      - name: B_table_name
        description: >
          Something 1
```
Without sorting `name` <-> `description` inside the folding block of level 4 and without squashing lines. Currently YAML-Sort returns:
``` yaml
---
models:
  - name: database_name
    tables:
      - description: |
          Something 1
        name: B_table_name
      - description: |
          Something 2
          * markdown item 1
          * markdown item 2
        meta:
          owner: me
        name: A_table_name
```
-> even with some extra `-`-ses and changes `>` to `|` which is okay, but it would be nicer to keep the original formatting. And (!) not sorting blocks between each other
