### ISSUE TITLE
[feature request] support line breaks

### ISSUE THREAD

**Issue by chimon2000** [pascalre/vscode-yaml-sort#11]
Currently when yaml is sorted, line breaks are removed.  It'd be nice to either maintain line breaks or have a config option to insert line breaks between keywords.  For instance

```yaml
name: app
description: A new application.

version: 1.0.0+2

environment:
  sdk: ">=2.6.0 <3.0.0"
```

instead of 

```
name: app
description: A new application.
version: 1.0.0+2
environment:
  sdk: ">=2.6.0 <3.0.0"
```
