### ISSUE TITLE
Custom sort only works for the top level

### ISSUE THREAD

**Issue by robbrad** [pascalre/vscode-yaml-sort#113]
Great extension in VSCode - works well in CloudFormation with the Schema applied - however for resources generally you want the type at the top under the resource name like so

```
Resources:
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Sub ${ProjectCodeName}-repo
```

Using Custom Sort only respects the top level and not the child levels

**Comment by bcouetil** [comment]
I have the same need, expressed in #100

**Comment by pascalre** [comment]
@robbrad please set the following settings (in Version 6.4.0):
```
    "vscode-yaml-sort.schema": "CLOUDFORMATION_SCHEMA",
    "vscode-yaml-sort.customSortKeywords_2": ["Type"],
    "vscode-yaml-sort.useCustomSortRecursively": true
```

Executing `Custom Sort 2` results in the following:

```
Resources:
  CodeCommitRepo:
    Type: 'AWS::CodeCommit::Repository'
    Properties:
      RepositoryName: !Sub '${ProjectCodeName}-repo'
```

I contributed a lot to this project in the last month, so I may resolved this bug without knowing it. Since this problem is not present anymore, I will close the issue. If you still got any troubles, please let me know!
