### ISSUE TITLE
[bug] trying to sort a nested dictionary results in removing it completely

### ISSUE THREAD

**Issue by ssbarnea** [pascalre/vscode-yaml-sort#12]
Apparently the only option to sort is to sort root level keys as for others this extension removes the lines.

```
artcl_commands:
  system:
    cpuinfo:
      capture_file: /var/log/extra/cpuinfo.txt
      cmd: cat /proc/cpuinfo
    dmesg:
      cmd: dmesg
    meminfo:
      capture_file: /var/log/extra/meminfo.txt
      cmd: cat /proc/meminfo
    pcs:
      cmd: |
        if type pcs &>/dev/null; then
          echo "+ pcs status"
          pcs status
          echo "+ pcs config"
          pcs config
        fi
    swaps:
      cmd: cat /proc/swaps
      capture_file: /var/log/extra/swaps.txt
    top:
      cmd: top -b -n 1
    rpm-list:
      cmd: rpm -qa | sort -f
    package-list-installed:
      cmd: "{{ ansible_pkg_mgr }} list installed"
      cmd: "{{ ansible_pkg_mgr }} repolist -v"
    selinux:
      cmd: /usr/sbin/getenforce
    installed_crons:
      cmd: |
        for user in $(cut -f1 -d':' /etc/passwd); do
        echo $user; crontab -u $user -l | grep -v '^$\|^\s*\#\|^\s*PATH'
        done
```

I am not sure what is confusing the sorting but I hope to be fixed as on big dics is very useful.
