### ISSUE TITLE
Custom sort recursively does not work with sort arrays.

### ISSUE THREAD

**Issue by huxuan** [pascalre/vscode-yaml-sort#136]
When enable both `Use Custom Sort Recursively` and `Sort Arrays`, it is supposed to apply custom sort arrays but actually not.

For example:

```yaml
python_version:
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
```

When enable both `Use Custom Sort Recursively` and `Sort Arrays`, with effective custom sort keys: 

```json
"vscode-yaml-sort.customSortKeywords_2": [
    "3.8",
    "3.9",
    "3.10",
    "3.11"
]
```

it will be formatted as following instead which is supposed to keep the original order.

```yaml
python_version:
  - '3.10'
  - '3.11'
  - '3.8'
  - '3.9'
```

BTW, objects work as expected.

**Comment by pascalre** [comment]
Hello @huxuan , the `customSortKeywords` does only apply for keywords and not for list items. I will keep this issue open, for a feature to custom sort lists.

**Comment by Ghostbird** [comment]
Tangentially related. I was trying to sort some infrastructure-as-code YAML with a custom sort definition that started with `name`. It would have been really nice if the array sort had sorted my list of services by _value_ of the first key. However, I think that in many situations that would make no sense at all, so I don't know exactly how to define a good sort order.

### Example
```yaml
services:
  - name: foo
    type: api
  - name: bar
    type: worker
```

When my custom sort definition is `name` or `name`, `type`, I'd like this to be sorted as:

```yaml
services:
  - name: bar
    type: worker
  - name: foo
    type: api
```

When my custom sort definition is `type` or `type`, `name`, I'd like this to be sorted as:

```yaml
services:
  - type: api
    name: foo
  - type: worker
    name: bar
```
