### ISSUE TITLE
Quoting removed when it shouldn't be

### ISSUE THREAD

**Issue by g-jozsef** [pascalre/vscode-yaml-sort#142]
Hi!

Formatting the following 
```
---
hello:
  stringField: asd
  stringField2: "asd"
  stringField3: "'{{ a }} - {{ b }}'"
```
returns 
```
---
hello:
  stringField: asd
  stringField2: asd
  stringField3: "{{ a }} - {{ b }}"
```
(still valid, but note 1 quote was removed from stringField2, and stringField3)
formatting again returns
```
---
hello:
  stringField: asd
  stringField2: asd
  stringField3: {{ a }} - {{ b }}
```
which is invalid yaml 
```
bad indentation of a mapping entry at line 5, column 25:
      stringField3: {{ a }} - {{ b }}
                            ^
```

I believe the extension should recognize that I want a quote there and not remove it.

NOTE:
formatting with ``"vscode-yaml-sort.forceQuotes": true,` does *not* put quotes around stringField3
```
---
hello:
  stringField: "asd"
  stringField2: "asd"
  stringField3: {{ a }} - {{ b }}
```

PS.: My use-case is to have "{{ a }} - {{ b }}" literal as a string

**Comment by pascalre** [comment]
Hello @g-jozsef, does it work for you when you use this setting: `"vscode-yaml-sort.useHelmProcessor": false` ?

**Comment by pascalre** [comment]
@g-jozsef in the latest release, you can keep double quotes

e. g.
```
---
hello:
  stringField: asd
  stringField2: "asd"
  stringField3: '"{{ a }} - {{ b }}"'
```

results in
```
---
hello:
  stringField: asd
  stringField2: asd
  stringField3: '"{{ a }} - {{ b }}"'
```
