### ISSUE TITLE
Sort YAML Converts `00000000-0000-0000-0000-000000000001` to octal

### ISSUE THREAD

**Issue by timendez** [pascalre/vscode-yaml-sort#159]
Repro:
```yaml
game:
  core:
    shardId: 00000000-0000-0000-0000-000000000001
```

converts to
```yaml
game:
  core:
    shardId: vscode-yaml-sort.octal.00000-0000-0000-0000-000000000001
```
