### ISSUE TITLE
Use block processor breaks on valid yaml

### ISSUE THREAD

**Issue by Striar-Yunis** [pascalre/vscode-yaml-sort#188]
In a file with the following yaml:

```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitor
resources:
  - bundle.yaml

patches:
  - target:
      kind: ClusterRoleBinding
      name: prometheus-operator
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: monitor
```

Enabling block processing results in:
```
bad indentation of a mapping entry (12:11)
  9 |       kind: ClusterRoleBinding
 10 |       name: prometheus-operator
 11 |     patch: vscode-yaml-sort.block.0
 12 |       - op: replace
----------------^
 13 |         path: /subjects/0/namespace
 14 |         value: monitor
```
