### ISSUE TITLE
First level keys not sorted by default with `sort yaml` command

### ISSUE THREAD

**Issue by UyttenhoveSimon** [pascalre/vscode-yaml-sort#193]
Hello,

First thanks for your extension. 
Second, apologies if such thing exists but I could not find a similar issue opened/closed or anything in the documentation.

Issue:

```yaml
nq:
  auth:
    org-organization-uuids:
      '7680': toto
    org-sso-ids:
      '7680': tata
  deployments:
    dashboard:
      api:
        key: 7df5f
        url: ${url}
      data:
        environment: UAT
        manifest-file: file:/data/workdir/manifest.json
      enabled: true
      
environment:
  name: Test
```

When using "sort yaml" command, the `nq` key and its child nodes are not placed below `environment` key.
If I use "Custom sort 1" it does the sorting as expected.

Is this behavior expected ?

Thanks in advance.
