### ISSUE TITLE
Problems with Formatting Azure DevOps Yaml File with template and parameters

### ISSUE THREAD

**Issue by pri-kise** [pascalre/vscode-yaml-sort#205]
Hi I want to use the extension with Azure DevOps Pipelines and want to use templates.

This is the result after formatting:

```yml
name: $(Build.BuildId)

variables:
  - group: Custom Settings

trigger: none

stages:
  - parameters:
      firstparamter: XXX
      secondparameter: YYY
    template: templates\CI.yml
```
This is the expected result: 
I'd like to have the `template` line before the `parameters` line.
```yml
name: $(Build.BuildId)

variables:
  - group: 'Custom Settings'

trigger: none

stages:
  - template: templates\CI.yml
    parameters:
      firstparamter: 'XXX'
      secondparameter: 'YYY'
```
