### ISSUE TITLE
Sorting error

### ISSUE THREAD

**Issue by ionesculiviucristian** [pascalre/vscode-yaml-sort#221]
Hello. The following yml file will fail sorting near `depends_on` with my vscode settings:
```json
{
  "vscode-yaml-sort.forceQuotes": true,
  "vscode-yaml-sort.quotingType": "\""
}
```

```yaml
services:
  # https://hub.docker.com/_/mysql
  mysql5:
    image: "mysql:5.7"
    restart: "unless-stopped"
    command:
      # https://dev.mysql.com/doc/refman/5.7/en/charset-server.html
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "${MYSQL5_PORT}:3306"
    environment:
      # https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html
      TZ: "${TZ?:err}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD?:err}"
      MYSQLD_EXPORTER_USER: "${MYSQLD_EXPORTER_USER?:err}"
      MYSQLD_EXPORTER_PASSWORD: "${MYSQLD_EXPORTER_PASSWORD?:err}"
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_DATABASE:
    volumes:
      - "./services/mysql/initdb:/docker-entrypoint-initdb.d"
      # - "./data/mysql5:/var/lib/mysql"
    healthcheck:
      test: '/usr/bin/mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute "SHOW DATABASES;"'
      interval: "5s"
      timeout: "5s"
      retries: 3
      start_period: "5s"
    networks:
      - "default"
      - "dp-mysql"
      - "dp-prometheus"

  # https://hub.docker.com/_/phpmyadmin
  # https://github.com/phpmyadmin/docker/tree/master/apache
  phpmyadmin5:
    image: "phpmyadmin:5.2"
    restart: "unless-stopped"
    environment:
      PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD:?err}"
      UPLOAD_LIMIT: "${PMA_UPLOAD_LIMIT:-2M}"
      PMA_USER: "root"
      PMA_HOSTS: "mysql5"
    depends_on:
      mysql5:
        condition: "service_healthy"
    networks:
      - "default"
      - "dp-traefik"
    labels:
      traefik.enable: true
      traefik.http.routers.services-phpmyadmin5.rule: "Host(`phpmyadmin5.services.localdev`)"
      traefik.http.routers.services-phpmyadmin5.entrypoints: "websecure"
      traefik.http.routers.services-phpmyadmin5.tls: true
      traefik.http.routers.services-phpmyadmin5.middlewares: "basic-auth@file"
      traefik.http.services.services-phpmyadmin5.loadbalancer.server.port: 80
      homepage.group: "Databases"
      homepage.name: "phpMyAdmin for MySQL v5"
      homepage.icon: "/icons/phpmyadmin.png"
      homepage.href: "https://phpmyadmin5.services.localdev"
      homepage.description: "phpMyAdmin is a free software tool written in PHP, intended to handle the administration of MySQL over the Web"

  # https://hub.docker.com/r/prom/mysqld-exporter
  mysqld_exporter5:
    image: "prom/mysqld-exporter:latest"
    command:
      - "--mysqld.address=mysql5:3306"
      - "--mysqld.username=${MYSQLD_EXPORTER_USER}"
      # https://github.com/prometheus/mysqld_exporter?tab=readme-ov-file#collector-flags
      - "--no-collect.slave_status"
    environment:
      MYSQLD_EXPORTER_USER: "${MYSQLD_EXPORTER_USER?:err}"
      MYSQLD_EXPORTER_PASSWORD: "${MYSQLD_EXPORTER_PASSWORD?:err}"
    depends_on:
      mysql5:
        condition: "service_healthy"
    networks:
      - "default"

networks:
  dp-traefik:
    external: true
  dp-mysql:
    external: true
  dp-prometheus:
    external: true
```
