### ISSUE TITLE
Inlined Comments are being removed upon sort

### ISSUE THREAD

**Issue by timendez** [pascalre/vscode-yaml-sort#222]
Test YAML:
```yaml
game:
  core:
    serviceRpcTimeoutMillis: 6900000 # Extra-long for debugging locally
```

Upon sorting this, it strips the comment and yields:
```yaml
game:
  core:
    serviceRpcTimeoutMillis: 6900000
```

thanks for the project! ❤️
