### ISSUE TITLE
Sorting messes up some strings

### ISSUE THREAD

**Issue by Skeeve** [pascalre/vscode-yaml-sort#227]
In my real world example I had a File which just looked similar to YAML in that it had a comment at the top.

So in order to make it a proper YAML, I made the comment a multiline string.

Unfortunately sorting messed the string and the file up.

Here is a working example.

# Original YAML:

```YAML
'!': |
    #####################################
    ##
    ## Zeta:
    ##     - C
    ##     - A
    ##     - B
    ## Beta:
    ##     - B
    ##     - C
    ##     - A
    ## Alpha:
    ##     - A
    ##     - B
    ##     - C
    ##
    #####################################

Zeta:
    - C
    - A
    - B
Beta:
    - B
    - C
    - A
Alpha:
    - A
    - B
    - C
```

# After Sorting

```YAML
---
'!': |
    #####################################
    ##
Alpha:
  - A
  - B
  - C
Beta:
  - B
  - C
  - A
Zeta:
  - C
  - A
  - B    ##
    ##     - A
    ## Alpha:
    ##     - C
    ##     - A
    ##     - B
    ## Beta:
    ##     - C
    ##     - A
    ##     - B
    ## Zeta:
    ##     - C
    #####################################
```
