### ISSUE TITLE
Un-quoted "on" and "off" strings are quoted after sorting YAML

### ISSUE THREAD

**Issue by raballew** [pascalre/vscode-yaml-sort#26]
When having keys and/or values like `on` and `off` within YAML files they get quoted when sorting the file. I expect this is due to the fact that in YAML 1.1 those keys evaluate to `true` or `false`. Anyway this has been dropped with YAML 1.2 and I would prefer using the latest specification instead of YAML 1.1.

The issue can easily be reproduced by sorting the following unsorted YAML file:

```yaml
---
key:
  on: foo
  off: egg
```

Sorted:

```yaml
---
key:
  'off': egg
  'on': foo
```

Expected:

```yaml
---
key:
  off: egg
  on: foo
```
