### ISSUE TITLE
[feature request] kubernetis friendly sort

### ISSUE THREAD

**Issue by freeseacher** [pascalre/vscode-yaml-sort#3]
Can you please add an option to sort options in a way that can be kubernetes manifests friendly.

by meaning so i am talking about sorting files like configmaps. let me describe problem. most of kubernets files starts with
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: activator-default
  name: activator-default
spec:
```
and so on. there can be clearly seen `api version` and `kind` also `metadata`. that info is pretty useful and have them in one place. 

but not for configmaps
they are lack of `spec` but use `data` attribute. so we will get
```
apiVersion: v1
data:
....
metadata:
  name: noc-configmap

```
where data can and probably will be pretty long. so during sort we have to define list of keys that should be unsorted and always on the top. 

that is only for top most keys. probably everything else should be sorted as always by alphabet
