### ISSUE TITLE
Add possibility to add specific custom sorts to file association

### ISSUE THREAD

**Issue by jorneilander** [pascalre/vscode-yaml-sort#32]
I have FluxCD project which incorporates a lot of YAML files which require a lot more than three custom sort sets to properly manage. It would be awesome to add some pre-defined and/or array of custom sorts and specifically reference them via file name. 

Example, the `.pre-commit.yaml` gets butchered, from: 
```YAML
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe]
      - id: check-added-large-files
```
to:
```YAML
repos:
  - hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - args:
          - '--allow-multiple-documents'
          - '--unsafe'
        id: check-yaml
      - id: check-added-large-files
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
```

But the repositoy also contains `kustomization`-files, `K8S`-files, `Home Assistant`-files, and some others. They all carry their own best practices in terms of readable sorting.
