### ISSUE TITLE
Custom sort of desired keys, then resume with alphabetical sort?

### ISSUE THREAD

**Issue by MadMaxMcKinney** [pascalre/vscode-yaml-sort#37]
Hello, I saw that there is a custom sort option that allows me to pass in a series of keys that I want to be sorted in a specific order. That said if you only pass in a few keys it only sorts those relative to each other once they appear alphabetically. 

For example, say I have this:

```yaml
- type: custom:button-card
            aspect_ratio: 1/1
            color_type: card
            color: '#1a759f'
            background: '#8d99ae'
            heading: 🚗 Driveway
            tap_action:
              action: navigate
              navigation_path: living-room
            icon: mdi:sofa
            show_name: false
            hold_action:
              action: none
```

I want to sort this alphabetically, but only after I sort a few specific keys. 

```
type
title
heading
```

**So I want to sort those specific keys to always be at the top of the list and in this order IF they appear, and then all other keys should be sorted alphabetically following them**. I would expect this:

```yaml
- type: custom:button-card
            heading: 🚗 Driveway
            aspect_ratio: 1/1
            background: '#8d99ae'
            color_type: card
            color: '#1a759f'
            hold_action:
              action: none
            icon: mdi:sofa
            show_name: false
            tap_action:
              action: navigate
              navigation_path: living-room
```

Instead though using those keys I provided to the custom sort I get this:

```yaml
- aspect_ratio: 1/1
            color: '#8d99ae'
            color_type: card
            hold_action:
              action: none
            heading: 🚗 Driveway
            icon: mdi:garage
            show_name: false
            tap_action:
              action: navigate
              navigation_path: driveway
            type: custom:button-card
```
