### ISSUE TITLE
Add support for Home Assistant schema

### ISSUE THREAD

**Issue by anoblet** [pascalre/vscode-yaml-sort#42]
Home Assistant uses custom tags. Please support custom tags such as the following:

```
example_key: !example_custom_tag example value
```

**Comment by pascalre** [comment]
@anoblet I can add a custom yaml schema with the tags used by Home Assistant. Can you provide a list of all custom tags Home Assistent currently supports? In my research I found these tags:

- `!env_var`
- `!include`
- `!include_dir_list`
- `!include_dir_merge_list`
- `!include_dir_merge_named`
- `!include_dir_*`

**Comment by anoblet** [comment]
I believe these are all of the custom tags that they use:

```
!env_var
!include
!include_dir_list
!include_dir_named
!include_dir_merge_list
!include_dir_merge_named
```

**Comment by pascalre** [comment]
@anoblet I just released version 5.2.0 including the fix. Please check out the version and let me know if this fits your needs. If you miss a custom tag, feel free to contribute to the [homeassistant-js-yaml-schema](https://github.com/pascalre/homeassistant-js-yaml-schema).
If you like this extension, I would really appreciate a review on the [marketplace](https://marketplace.visualstudio.com/items?itemName=PascalReitermann93.vscode-yaml-sort&ssr=false#review-details). 😊

**Comment by pascalre** [comment]
Forgot to mention: You need to set `vscode-yaml-sort.schema` to `HOMEASSISTANT_SCHEMA` to use this feature.

**Comment by anoblet** [comment]
@pascalre I forgot one!

`!secret`

**Comment by pascalre** [comment]
@anoblet update to version 5.3.1

**Comment by anoblet** [comment]
I tried using the HOMEASSISTANT_SCHEMA today, and realized that it does not format correctly:

```
type: custom:flex-card
cards:
  - type: custom:generic-card
    class: relative
    cards:
      - !include bathroom/temperature.yaml
    title: Temperature
```

->

```
cards:
  - cards:
      - !include 
        class: include
        data: bathroom/temperature.yaml
        name: include
    class: relative
    title: Temperature
    type: custom:generic-card
type: custom:flex-card
```
`- !include bathroom/temperature.yaml` should stay on it's own line with no modifications.
