### ISSUE TITLE
emptyLinesUntilLevel doesn't work with keys containing spaces

### ISSUE THREAD

**Issue by schlomo** [pascalre/vscode-yaml-sort#44]
```yaml
Brand:
  baz: blub
Some blubtest:
  another: key

foo:
  test: 2
```

is the result of sorting with these settings:

```json
    "vscode-yaml-sort.emptyLinesUntilLevel": 1,
    "vscode-yaml-sort.useLeadingDashes": false,
```

When I remove the space in `Some blubtest` then it works correctly:
```yaml
Brand:
  baz: blub

Someblubtest:
  another: key

foo:
  test: 2
```

Using YAML Sort `v5.1.6`
