### ISSUE TITLE
yaml sort executes all blocks and merges making DRY inpossible

### ISSUE THREAD

**Issue by reneweteling** [pascalre/vscode-yaml-sort#55]
on sort, all merge blocks are executed: https://yaml.org/type/merge.html

## Before sort

```yml
nl:
  default: &default
    somekey: is a value
  generic:
    <<: *default
    some_other_key: also a value
````     

## After sort
```yml
---
nl:
  default:
    somekey: is a value
  generic:
    some_other_key: also a valu
    somekey: is a value
```

So the block is gone, and the values are being inserted, this makes the yml sort unusable in big dry yml files.
