### ISSUE TITLE
[bug] Sorting tabs indented yaml removes code

### ISSUE THREAD

**Issue by svyotov** [pascalre/vscode-yaml-sort#9]
Using this tool on visual studio, resulted in all the YAML being deleted.
VS code reported that there was an internal bug in the YAML, specifically that there was a duplicated key (there was not, all the parent keys are unique).
If there are such issues, it should keep the code as is before the sort.

Update: after debugging I deducted that the actual issue was that the YAML was tab formated.

Sample:

```yaml
a-1:
	b:
		d: g
	c:
		d: g
a-2:
	b:
		d: g
	c:
		d: g
b:
	b:
		d: g
	c:
		d: g
```
